apiVersion: apps/v1
kind: Deployment
metadata:
  name: candle-app
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: candle-app
  template:
    metadata:
      labels:
        app: candle-app
    spec:
      containers:
      - name: app
        image: {{ .Values.app.image }}
        imagePullPolicy: Always