apiVersion: apps/v1
kind: Deployment
metadata:
  name: candle-web
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app: candle-web
  template:
    metadata:
      labels:
        app: candle-web
    spec:
      serviceAccountName: web-log-reader
      containers:
      - name: web
        image: {{ .Values.web.image }}
        imagePullPolicy: Always
        ports:
        - containerPort: 80